sudo: required
notifications:
  email: false
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_f73069fb71a8_key -iv $encrypted_f73069fb71a8_iv
  -in deploy_key.enc -out ./deploy_key -d
- docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
- openssl aes-256-cbc -K $encrypted_ced0c438de4d_key -iv $encrypted_ced0c438de4d_iv
  -in deploy_key.enc -out ./deploy_key -d
- docker build -t timcole.me .
- docker run -d --name app timcole.me
- docker ps -a
script:
- docker tag timcole.me:latest $DOCKER_HUB_USERNAME/timcole.me:production
- docker push $DOCKER_HUB_USERNAME/timcole.me:production
after_script:
- docker rm -f app
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && ssh -o StrictHostKeyChecking=no -i ./deploy_key
    tim@pepega.tcole.me './deploy.sh'
  on:
    branch: testing/travis
env:
  global:
  - secure: I1+czJ1iM3bBg8OB0oiup7gRHYC3gI2TiOOX8eIr6oedWoAnzBR0ytIOorfcqrkESo//iYDbiA6hBTemkahcTHbcKiU9HfH43lTxcEso+/Gf7YlNQ917ZLR4SHtR+GN/wdOQEZr+HcVeZrgbG268IhZ5dSWy+YiRB0asV09HElaveCZySIiIOIZQddw5bRnsRTjkLWh16nk/mCoEj4wpxNN8cdNVX5DfdasI2dl5m+3ddbX7NDJoD5cN6kfXPsbsxdjz8so7ALKEiTwjaywtFKYFNQH8tR1U73hvdpo9Dgy9Jv7LOig5pSMXul2B77/NQw5ApHqGyjCurYMji+vMjDQ9gwyWmnA6WqxPklKxl6c9es/a+HYo4WyUbOLvRyfZN1Gn15LPXS3CDVcT2H8Yn9OvYiHNYBamBKClk8RYYqnZOOkxA/5pRVixUGrjv2AQZUXrvp1Rvxyah90inH9dUEna+cj95D6Z2LQbcTzxhGaL6fMf7LokddSh/WL2VvGVyi/Fxzh+EWEy/vFGyyzGp7g3WftIFCjBU4hGvU6zhdYqADwXR9QsS7F/Yy20m5O4IlxVLolPdrpjyRpu4bDtV55FDJnbMCfHHWHJzHUrWuQUKQ81tf5YTyI2eP/ZwJpy4JaLtISR3ZlB6f6AYdj924C9WVmnffsYaZzhvn+GqLY=
  - secure: FWwjKvCuakUCxGAvTDVV3qb5HSmV6hUMTZR63aH4lXUAF2fWf+96qUmoaCVFSyq7dnX7ybcNdM8W55liCruBcdrfTVpN4OKC+hir+7s/2tr8SDVrPT0xBnvg88bdMUPzYt66tBxDCCRiXCJS7PXlt+q71FYWvAQCGkrFUPh+bFANgh14GcRS9REcS3sqXSg4xQ048Uc4duiR4EU/AKWaRSGnrP8LLIBxwfoci/08/XJCfUv3neiysZwbPIF6fanM09XTzRIDsl4I8DdlSRhObcNQTeVCYLxSKC6+4VcO+jebZX6mW6L9WG2zpsJmpIMSgGOnehPdKGvXmk5x1QcGmoKbr5az2ihrcZCzXLc49/dU5G/oUH/3CyjXdXx8Ks+VwbXz+t9tp865DPi4JsfZpGaFNU5jBRudmTo52a1zLZzj+GeJs/8+TnHDmRLMKDtnGl5SOEo6wIcfiSBHtrOJ0W5/zaWPbc9hGXM6WxQB7GnEczEWdT5bdo/X97TWCEz8TlLP0qHqhetPp1+c+6Uh6yS/QVEpsitH3LnhzT6qASsjVQUf/0THs5Diseabikkg4Qn05gHjhvWm8BlZbElFDDMNkueiGP4Z9HXs/VUL01xY+a+NqtkzY5h7rPHLmFAutFlIY80dB8pItO1V2PTeVIJpOHIJwQ6IFHflE19h0Rs=
