notifications:
  email: false

jobs:
  include:
  - language: go
    go: 1.9.x
    script:
    - go install ./...
  - language: go
    go: 1.10.x
    script:
    - go install ./...
    - go test -v -race ./...